<?php
/**
 * @file
 * File.
 */

use \Drupal\d8_adyax_test\Entity\D8AdyaxTest;
use \Drupal\taxonomy\Entity\Term;
use \Drupal\taxonomy\Entity\Vocabulary;


/**
 * Implements hook_install().
 */
function d8_adyax_test_install() {
  $vid = 'brands';
  $vocabulary_name = 'Brands';
  $brands = ['mazda','renault','toyota','ZAZ'];

  $number_of_entities = 15;
  $counter = 0;
  $names = [
    'Jeorge',
    'Nick',
    'Alla',
    'Ivan',
    'Zoe',
    'Pavel',
  ];


  $vocabulary = Vocabulary::create(array(
    'vid' => $vid,
    'machine_name' => $vid,
    'name' => $vocabulary_name,
  ));
  $vocabulary->save();
  foreach ($brands as $brand) {
    Term::create(array(
      'parent' => array(),
      'name' => $brand,
      'vid' => $vid,
    ))->save();
  }

  $terms = \Drupal::entityTypeManager()
    ->getStorage('taxonomy_term')
    ->loadTree($vid);
  foreach ($terms as $term) {
    $voc[] = $term->tid;
  }

  while ($counter < $number_of_entities) {
    $new_entity = D8AdyaxTest::create([
      'client_name' => $names[rand(0, (count($names) - 1))],
      'products_owned_count' => rand(0, 15),
      'prefered_brand' => [$voc[rand(0, (count($voc) - 1))]],
    ]);
    $new_entity->setOwnerId(1)
      ->enforceIsNew()
      ->save();
    $counter++;
  }

}

/**
 * Implements hook_uninstall().
 */
function d8_adyax_test_uninstall() {

  $tids = \Drupal::entityQuery('taxonomy_term')
    ->condition('vid', 'brands')
    ->execute();

  $controller = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $terms = $controller->loadMultiple($tids);
  $controller->delete($terms);

  Vocabulary::load('brands')->delete();

}

/**
 * Implements hook_update_N().
 *
 * Adds field in entity Adyax Test.
 */
function d8_adyax_test_update_8001() {
  \Drupal::entityDefinitionUpdateManager()->applyUpdates();
}

/**
 * Implements hook_update_N().
 *
 * Changes field in entity Adyax Test.
 */
function d8_adyax_test_update_8002() {

  $query = \Drupal::database()->update('d8_adyax_test');
  $query->isNull('date');
  $query->fields([
    'date' => time() - 30 * 24 * 60 * 60,
  ]);
  $query->execute();
}

/**
 * Implements hook_update_N().
 *
 * Changes field in entity Adyax Test.
 */
function d8_adyax_test_update_8003() {

  $query = \Drupal::database()->update('d8_adyax_test');
  $query->fields([
    'date' => time(),
  ]);
  $query->condition('date', (time() - 10 * 24 * 60 * 60), '<');
  $query->execute();

}
